# Generated by Django 4.2.24 on 2025-10-13 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_owner_account"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="owner",
            options={"verbose_name": "Owner", "verbose_name_plural": "Owners"},
        ),
    ]
