# Generated by Django 4.2.25 on 2025-10-20 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0002_est_habitat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="owner",
            name="user",
        ),
        migrations.AddField(
            model_name="owner",
            name="users",
            field=models.ManyToManyField(blank=True, related_name="owners", to=settings.AUTH_USER_MODEL),
        ),
    ]
