# Generated by Django 4.2.27 on 2026-01-20 15:15
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("account", "0004_student_studentregistrationtoken"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX unique_user_email_not_empty
                ON auth_user (email)
                WHERE email <> '';
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS unique_user_email_not_empty;
            """,
        ),
    ]
