# Generated by Django 4.2.27 on 2026-02-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_auto_20260120_1515"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="dossierfacile_linked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="dossierfacile_tenant_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
