# Generated by Django 4.2.27 on 2026-02-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_auto_20260120_1515"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="accept_dossier_facile_applications",
            field=models.BooleanField(default=False),
        ),
    ]
