# Generated by Django 4.2.27 on 2026-02-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_student_dossierfacile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="dossierfacile_last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="dossierfacile_pdf_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="dossierfacile_status",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="dossierfacile_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
