default_language_version:
  python: python3.13
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/thoughtworks/talisman
    rev: v1.37.0
    hooks:
      - id: talisman-commit
  - repo: https://github.com/devanshshukla99/pre-commit-hook-prohibit-string
    rev: v1.2
    hooks:
      - id: prohibit-string
        args: [--prohibit-string, "DONOTCOMMIT,DO NOT COMMIT"]
        files: '.*'
        message: "🚫 Your code contains DONOTCOMMIT. Please remove it before committing."
