# Generated by Django 4.2.27 on 2026-02-24 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0006_owner_accept_dossier_facile_applications"),
        ("accommodation", "0050_accommodationapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="DossierFacileTenant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("access_revoked", "Access Revoked"),
                            ("denied", "Denied"),
                            ("verified", "Verified"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                ("pdf_url", models.URLField(blank=True, max_length=500, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dossier_facile_tenants",
                        to="account.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DossierFacileApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "appartment_type",
                    models.CharField(
                        choices=[
                            ("t1", "T1"),
                            ("t1_bis", "T1 Bis"),
                            ("t2", "T2"),
                            ("t3", "T3"),
                            ("t4", "T4"),
                            ("t5", "T5"),
                            ("t6", "T6"),
                            ("t7_more", "T7 More"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accommodation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dossier_facile_applications",
                        to="accommodation.accommodation",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="dossier_facile.dossierfaciletenant",
                    ),
                ),
            ],
        ),
    ]
