# Generated by Django 4.2.27 on 2026-03-02 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dossier_facile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DossierFacileOAuthState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.CharField(db_index=True, max_length=255, unique=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dossier_facile_oauth_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
