# Generated by Codex on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dossier_facile", "0002_dossierfacileoauthstate"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="dossierfaciletenant",
            constraint=models.UniqueConstraint(
                fields=("student", "tenant_id"),
                name="unique_dossier_facile_tenant_per_student",
            ),
        ),
    ]
