# Generated by Django 4.2.27 on 2026-03-02 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0002_add_event_stats"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="eventstats",
            new_name="stats_event_period_045d19_idx",
            old_name="stats_event_period_idx",
        ),
        migrations.RenameIndex(
            model_name="eventstats",
            new_name="stats_event_categor_75ae9e_idx",
            old_name="stats_event_cat_action_idx",
        ),
        migrations.RenameIndex(
            model_name="stats",
            new_name="stats_stats_period_c2c1b0_idx",
            old_name="stats_stats_period_5c5b69_idx",
        ),
        migrations.RenameIndex(
            model_name="stats",
            new_name="stats_stats_created_aba840_idx",
            old_name="stats_stats_created_6f1d3e_idx",
        ),
    ]
