# Generated by Django 4.2.27 on 2026-03-03 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_auto_20260120_1515"),
        ("accommodation", "0053_accommodation_target_audience_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stats", "0003_rename_stats_event_period_idx_stats_event_period_045d19_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GestionnaireLoginEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("logged_in_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_events",
                        to="account.owner",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-logged_in_at"],
                "indexes": [
                    models.Index(fields=["owner", "-logged_in_at"], name="stats_gesti_owner_i_95256c_idx"),
                    models.Index(fields=["user", "-logged_in_at"], name="stats_gesti_user_id_4dc8e9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AccommodationChangeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("created", "Created"), ("updated", "Updated")], max_length=20)),
                ("data_diff", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "accommodation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="accommodation.accommodation",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accommodation_change_logs",
                        to="account.owner",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accommodation_change_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["owner", "-created_at"], name="stats_accom_owner_i_fc88c9_idx"),
                    models.Index(fields=["accommodation", "-created_at"], name="stats_accom_accommo_c40292_idx"),
                    models.Index(fields=["action", "-created_at"], name="stats_accom_action_ba3cde_idx"),
                ],
            },
        ),
    ]
