# Generated by Django 4.2.23 on 2025-07-21 14:13

import autoslug.fields
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("accommodation", "0001_accomodations_and_external_source"),
        ("accommodation", "0002_accomodations_and_external_source"),
        ("accommodation", "0003_accomodations_published"),
        ("accommodation", "0004_accommodation_slug"),
        ("accommodation", "0005_accommodation_slug_unique"),
        ("accommodation", "0006_accommodation_images"),
        ("accommodation", "0007_owner"),
        ("accommodation", "0008_accommodation_price_min"),
        ("accommodation", "0009_accommodation_equipments"),
        ("accommodation", "0010_accommodation_equipments"),
        ("accommodation", "0011_accommodation_source"),
        ("accommodation", "0012_accommodation_null_equipments"),
        ("accommodation", "0013_externalsource_null_sourceid"),
        ("accommodation", "0014_images_count"),
        ("accommodation", "0015_sogima"),
        ("accommodation", "0016_images_urls"),
        ("accommodation", "0017_price_min_indexes"),
        ("accommodation", "0018_images_count_published_indexes"),
        ("accommodation", "0019_images_removal"),
        ("accommodation", "0020_accommodation_available"),
        ("accommodation", "0021_source_ohmonappart"),
        ("accommodation", "0022_source_evolea"),
        ("accommodation", "0023_nb_available"),
        ("accommodation", "0024_tarn_habitat"),
        ("accommodation", "0025_seqens_parme"),
        ("accommodation", "0026_source_nantes_vendee"),
        ("accommodation", "0027_france_loire"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="Localisation"
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=150)),
                ("postal_code", models.CharField(max_length=5)),
                (
                    "residence_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("universitaire-conventionnee", "Résidence Universitaire conventionnée"),
                            ("sociale-jeunes-actifs", "Résidence sociale Jeunes Actifs"),
                            ("intergenerationnelle", "Résidence intergénérationnelle"),
                            ("autre", "Autre"),
                            ("jeunes-travailleurs", "Foyer Jeunes Travailleurs"),
                            ("service-universitaire-privee", "Résidence service / Résidence universitaire privée"),
                            ("mixte-actifs-etudiants", "Résidence mixte jeunes actifs/étudiants"),
                            ("u-crous", "Cité U / résidence traditionnelle CROUS"),
                            ("hoteliere-sociale", "Résidence Hôtelière à vocation sociale"),
                            ("ecole", "Résidence d'école"),
                            ("service-logement", "Service Logement"),
                            ("internat", "Internat"),
                            ("foyer-soleil", "Foyer soleil"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("owner_name", models.CharField(blank=True, max_length=150, null=True)),
                ("owner_url", models.CharField(blank=True, max_length=500, null=True)),
                ("nb_total_apartments", models.IntegerField(blank=True, null=True)),
                ("nb_accessible_apartments", models.IntegerField(blank=True, null=True)),
                ("nb_coliving_apartments", models.IntegerField(blank=True, null=True)),
                ("nb_t1", models.IntegerField(blank=True, null=True)),
                ("nb_t1_bis", models.IntegerField(blank=True, null=True)),
                ("nb_t2", models.IntegerField(blank=True, null=True)),
                ("nb_t3", models.IntegerField(blank=True, null=True)),
                ("nb_t4_more", models.IntegerField(blank=True, null=True)),
                ("published", models.BooleanField(default=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(default="", editable=False, max_length=255, populate_from="name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source",
                    models.CharField(
                        choices=[("acceslibre", "Accèslibre"), ("clef", "CLEF")],
                        default="clef",
                        max_length=100,
                        verbose_name="Source",
                    ),
                ),
                ("source_id", models.CharField(max_length=100, verbose_name="Source ID")),
                (
                    "accommodation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="accommodation.accommodation",
                    ),
                ),
            ],
            options={
                "unique_together": {("source", "accommodation")},
            },
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="", editable=False, max_length=255, populate_from="name", unique=True
            ),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="images",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.BinaryField(), blank=True, null=True, size=None
            ),
        ),
        migrations.RemoveField(
            model_name="accommodation",
            name="owner_name",
        ),
        migrations.RemoveField(
            model_name="accommodation",
            name="owner_url",
        ),
        migrations.AddField(
            model_name="accommodation",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accommodations",
                to="account.owner",
            ),
        ),
        migrations.AlterField(
            model_name="externalsource",
            name="source",
            field=models.CharField(
                choices=[("acceslibre", "Accèslibre"), ("clef", "CLEF"), ("agefo", "Agefo")],
                default="clef",
                max_length=100,
                verbose_name="Source",
            ),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_min_t1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_max_t1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_max_t1_bis",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_max_t2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_max_t3",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_max_t4_more",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_min_t1_bis",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_min_t2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_min_t3",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_min_t4_more",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="bathroom",
            field=models.CharField(
                blank=True, choices=[("shared", "Shared"), ("private", "Private")], max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="external_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="kitchen_type",
            field=models.CharField(
                blank=True, choices=[("shared", "Shared"), ("private", "Private")], max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="externalsource",
            name="source",
            field=models.CharField(
                choices=[("acceslibre", "Accèslibre"), ("clef", "CLEF"), ("agefo", "Agefo"), ("espacil", "Espacil")],
                default="clef",
                max_length=100,
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="externalsource",
            name="source",
            field=models.CharField(
                choices=[
                    ("acceslibre", "Accèslibre"),
                    ("clef", "CLEF"),
                    ("agefo", "Agefo"),
                    ("espacil", "Espacil"),
                    ("arpej", "Arpej"),
                ],
                default="clef",
                max_length=100,
                verbose_name="Source",
            ),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="bike_storage",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="common_areas",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="cooking_plates",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="desk",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="laundry_room",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="microwave",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="parking",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="refrigerator",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="residence_manager",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="secure_access",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="externalsource",
            name="source",
            field=models.CharField(
                choices=[
                    ("acceslibre", "Accèslibre"),
                    ("clef", "CLEF"),
                    ("agefo", "Agefo"),
                    ("espacil", "Espacil"),
                    ("arpej", "Arpej"),
                    ("studefi", "Studefi"),
                ],
                default="clef",
                max_length=100,
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="externalsource",
            name="source_id",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Source ID"),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="images_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="accommodation",
            index=models.Index(fields=["-images_count"], name="accommodati_images__5c8955_idx"),
        ),
        migrations.AlterField(
            model_name="externalsource",
            name="source",
            field=models.CharField(
                choices=[
                    ("acceslibre", "Accèslibre"),
                    ("clef", "CLEF"),
                    ("agefo", "Agefo"),
                    ("espacil", "Espacil"),
                    ("arpej", "Arpej"),
                    ("studefi", "Studefi"),
                    ("sogima", "Sogima"),
                ],
                default="clef",
                max_length=100,
                verbose_name="Source",
            ),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="images_urls",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_min",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_accessible_apartments",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_coliving_apartments",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.RemoveIndex(
            model_name="accommodation",
            name="accommodati_images__5c8955_idx",
        ),
        migrations.AddIndex(
            model_name="accommodation",
            index=models.Index(fields=["published", "-images_count"], name="accommodati_publish_7d5dc3_idx"),
        ),
        migrations.RemoveField(
            model_name="accommodation",
            name="images",
        ),
        migrations.AddField(
            model_name="accommodation",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="externalsource",
            name="source",
            field=models.CharField(
                choices=[
                    ("acceslibre", "Accèslibre"),
                    ("clef", "CLEF"),
                    ("agefo", "Agefo"),
                    ("espacil", "Espacil"),
                    ("arpej", "Arpej"),
                    ("studefi", "Studefi"),
                    ("sogima", "Sogima"),
                    ("orne-habitat", "Orne Habitat"),
                ],
                default="clef",
                max_length=100,
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="externalsource",
            name="source",
            field=models.CharField(
                choices=[
                    ("acceslibre", "Accèslibre"),
                    ("clef", "CLEF"),
                    ("agefo", "Agefo"),
                    ("espacil", "Espacil"),
                    ("arpej", "Arpej"),
                    ("studefi", "Studefi"),
                    ("sogima", "Sogima"),
                    ("orne-habitat", "Orne Habitat"),
                    ("oh-mon-appart", "Oh Mon Appart"),
                ],
                default="clef",
                max_length=100,
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="externalsource",
            name="source",
            field=models.CharField(
                choices=[
                    ("acceslibre", "Accèslibre"),
                    ("clef", "CLEF"),
                    ("agefo", "Agefo"),
                    ("espacil", "Espacil"),
                    ("arpej", "Arpej"),
                    ("studefi", "Studefi"),
                    ("sogima", "Sogima"),
                    ("orne-habitat", "Orne Habitat"),
                    ("oh-mon-appart", "Oh Mon Appart"),
                    ("evolea", "Evolea"),
                ],
                default="clef",
                max_length=100,
                verbose_name="Source",
            ),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="nb_t1_available",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="nb_t1_bis_available",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="nb_t2_available",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="nb_t3_available",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="nb_t4_more_available",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="externalsource",
            name="source",
            field=models.CharField(
                choices=[
                    ("acceslibre", "Accèslibre"),
                    ("clef", "CLEF"),
                    ("agefo", "Agefo"),
                    ("espacil", "Espacil"),
                    ("arpej", "Arpej"),
                    ("studefi", "Studefi"),
                    ("sogima", "Sogima"),
                    ("orne-habitat", "Orne Habitat"),
                    ("tarn-habitat", "Tarn Habitat"),
                    ("oh-mon-appart", "Oh Mon Appart"),
                    ("evolea", "Evolea"),
                ],
                default="clef",
                max_length=100,
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="externalsource",
            name="source",
            field=models.CharField(
                choices=[
                    ("acceslibre", "Accèslibre"),
                    ("clef", "CLEF"),
                    ("agefo", "Agefo"),
                    ("espacil", "Espacil"),
                    ("arpej", "Arpej"),
                    ("studefi", "Studefi"),
                    ("sogima", "Sogima"),
                    ("orne-habitat", "Orne Habitat"),
                    ("tarn-habitat", "Tarn Habitat"),
                    ("oh-mon-appart", "Oh Mon Appart"),
                    ("evolea", "Evolea"),
                    ("partelios", "Partelios"),
                    ("seqens", "Seqens/Adlis"),
                    ("parme", "Parme"),
                ],
                default="clef",
                max_length=100,
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="externalsource",
            name="source",
            field=models.CharField(
                choices=[
                    ("acceslibre", "Accèslibre"),
                    ("clef", "CLEF"),
                    ("agefo", "Agefo"),
                    ("espacil", "Espacil"),
                    ("arpej", "Arpej"),
                    ("studefi", "Studefi"),
                    ("sogima", "Sogima"),
                    ("orne-habitat", "Orne Habitat"),
                    ("tarn-habitat", "Tarn Habitat"),
                    ("oh-mon-appart", "Oh Mon Appart"),
                    ("evolea", "Evolea"),
                    ("partelios", "Partelios"),
                    ("seqens", "Seqens/Adlis"),
                    ("parme", "Parme"),
                    ("bmh", "Brest Métropole Habitat"),
                    ("nantaise", "Nantaise d'habitation"),
                    ("vendee", "Vendée logement"),
                ],
                default="clef",
                max_length=100,
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="externalsource",
            name="source",
            field=models.CharField(
                choices=[
                    ("acceslibre", "Accèslibre"),
                    ("clef", "CLEF"),
                    ("agefo", "Agefo"),
                    ("espacil", "Espacil"),
                    ("arpej", "Arpej"),
                    ("studefi", "Studefi"),
                    ("sogima", "Sogima"),
                    ("orne-habitat", "Orne Habitat"),
                    ("tarn-habitat", "Tarn Habitat"),
                    ("oh-mon-appart", "Oh Mon Appart"),
                    ("evolea", "Evolea"),
                    ("partelios", "Partelios"),
                    ("seqens", "Seqens/Adlis"),
                    ("parme", "Parme"),
                    ("bmh", "Brest Métropole Habitat"),
                    ("nantaise", "Nantaise d'habitation"),
                    ("vendee", "Vendée logement"),
                    ("france-loire", "France Loire"),
                ],
                default="clef",
                max_length=100,
                verbose_name="Source",
            ),
        ),
    ]
