# Generated by Django 4.2.17 on 2024-12-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0001_accomodations_and_external_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accommodation",
            name="nb_accessible_apartments",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_coliving_apartments",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t1_bis",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t3",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t4_more",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_total_apartments",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="owner_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="owner_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="residence_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "universitaire-conventionnee",
                        "Résidence Universitaire conventionnée",
                    ),
                    ("sociale-jeunes-actifs", "Résidence sociale Jeunes Actifs"),
                    ("intergenerationnelle", "Résidence intergénérationnelle"),
                    ("autre", "Autre"),
                    ("jeunes-travailleurs", "Foyer Jeunes Travailleurs"),
                    (
                        "service-universitaire-privee",
                        "Résidence service / Résidence universitaire privée",
                    ),
                    (
                        "mixte-actifs-etudiants",
                        "Résidence mixte jeunes actifs/étudiants",
                    ),
                    ("u-crous", "Cité U / résidence traditionnelle CROUS"),
                    ("hoteliere-sociale", "Résidence Hôtelière à vocation sociale"),
                    ("ecole", "Résidence d'école"),
                    ("service-logement", "Service Logement"),
                    ("internat", "Internat"),
                    ("foyer-soleil", "Foyer soleil"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
