# Generated by Django 4.2.17 on 2024-12-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0002_accomodations_and_external_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externalsource",
            name="published",
        ),
        migrations.AddField(
            model_name="accommodation",
            name="published",
            field=models.BooleanField(default=True),
        ),
    ]
