# Generated by Django 4.2.17 on 2024-12-16 09:01

import autoslug.fields
from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Accommodation = apps.get_model("accommodation", "Accommodation")
    existing_slugs = set()
    for obj in Accommodation.objects.all():
        base_slug = slugify(obj.name)[:255]
        slug = base_slug
        counter = 1
        while slug in existing_slugs or Accommodation.objects.filter(slug=slug).exists():
            suffix = f"-{counter}"
            slug = f"{base_slug[:255 - len(suffix)]}{suffix}"
            counter += 1
        obj.slug = slug
        obj.save()
        existing_slugs.add(slug)


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0003_accomodations_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="", editable=False, populate_from="name", unique=False, max_length=255
            ),
        ),
        migrations.RunPython(populate_slugs),
    ]
