# Generated by Django 4.2.18 on 2025-03-03 10:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0005_accommodation_slug_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="images",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.BinaryField(), blank=True, null=True, size=None
            ),
        ),
    ]
