# Generated by Django 4.2.18 on 2025-03-04 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "__first__"),
        ("accommodation", "0006_accommodation_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accommodation",
            name="owner_name",
        ),
        migrations.RemoveField(
            model_name="accommodation",
            name="owner_url",
        ),
        migrations.AddField(
            model_name="accommodation",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accommodations",
                to="account.owner",
            ),
        ),
    ]
