# Generated by Django 4.2.20 on 2025-03-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0007_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="price_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="externalsource",
            name="source",
            field=models.CharField(
                choices=[("acceslibre", "Accèslibre"), ("clef", "CLEF"), ("agefo", "Agefo")],
                default="clef",
                max_length=100,
                verbose_name="Source",
            ),
        ),
    ]
