# Generated by Django 4.2.20 on 2025-03-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0008_accommodation_price_min"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accommodation",
            old_name="price_min",
            new_name="price_min_t1",
        ),
        migrations.AddField(
            model_name="accommodation",
            name="bathroom_shared_or_private",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="bike_storage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="common_areas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="cooking_plates",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="desk",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="kitchen_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="laundry_room",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="microwave",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="parking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_max_t1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_max_t1_bis",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_max_t2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_max_t3",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_max_t4_more",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_min_t1_bis",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_min_t2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_min_t3",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_min_t4_more",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="refrigerator",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="residence_manager",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="secure_access",
            field=models.BooleanField(default=False),
        ),
    ]
