# Generated by Django 4.2.20 on 2025-03-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0009_accommodation_equipments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accommodation",
            name="bathroom_shared_or_private",
        ),
        migrations.AddField(
            model_name="accommodation",
            name="bathroom",
            field=models.CharField(
                blank=True, choices=[("shared", "Shared"), ("private", "Private")], max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="external_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="kitchen_type",
            field=models.CharField(
                blank=True, choices=[("shared", "Shared"), ("private", "Private")], max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="externalsource",
            name="source",
            field=models.CharField(
                choices=[("acceslibre", "Accèslibre"), ("clef", "CLEF"), ("agefo", "Agefo"), ("espacil", "Espacil")],
                default="clef",
                max_length=100,
                verbose_name="Source",
            ),
        ),
    ]
