# Generated by Django 4.2.20 on 2025-03-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0010_accommodation_equipments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalsource",
            name="source",
            field=models.CharField(
                choices=[
                    ("acceslibre", "Accèslibre"),
                    ("clef", "CLEF"),
                    ("agefo", "Agefo"),
                    ("espacil", "Espacil"),
                    ("arpej", "Arpej"),
                ],
                default="clef",
                max_length=100,
                verbose_name="Source",
            ),
        ),
    ]
