# Generated by Django 4.2.20 on 2025-04-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0012_accommodation_null_equipments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalsource",
            name="source",
            field=models.CharField(
                choices=[
                    ("acceslibre", "Accèslibre"),
                    ("clef", "CLEF"),
                    ("agefo", "Agefo"),
                    ("espacil", "Espacil"),
                    ("arpej", "Arpej"),
                    ("studefi", "Studefi"),
                ],
                default="clef",
                max_length=100,
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="externalsource",
            name="source_id",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Source ID"),
        ),
    ]
