# Generated by Django 4.2.20 on 2025-04-29 10:09

from django.conf import settings
from django.db import migrations, models


def populate_images_count(apps, schema_editor):
    if settings.TEST:
        return
    Accommodation = apps.get_model("accommodation", "Accommodation")
    for acc in Accommodation.objects.all():
        acc.save()


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0013_externalsource_null_sourceid"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="images_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="accommodation",
            index=models.Index(fields=["-images_count"], name="accommodati_images__5c8955_idx"),
        ),
        migrations.RunPython(populate_images_count, reverse_code=populate_images_count),
    ]
