# Generated by Django 4.2.20 on 2025-05-05 09:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0015_sogima"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="images_urls",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), blank=True, null=True, size=None
            ),
        ),
    ]
