# Generated by Django 4.2.20 on 2025-05-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0016_images_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="price_min",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_accessible_apartments",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_coliving_apartments",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
