# Generated by Django 4.2.20 on 2025-05-13 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0018_images_count_published_indexes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accommodation",
            name="images",
        ),
    ]
