# Generated by Django 4.2.21 on 2025-06-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0019_images_removal"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="externalsource",
            name="source",
            field=models.CharField(
                choices=[
                    ("acceslibre", "Accèslibre"),
                    ("clef", "CLEF"),
                    ("agefo", "Agefo"),
                    ("espacil", "Espacil"),
                    ("arpej", "Arpej"),
                    ("studefi", "Studefi"),
                    ("sogima", "Sogima"),
                    ("orne-habitat", "Orne Habitat"),
                ],
                default="clef",
                max_length=100,
                verbose_name="Source",
            ),
        ),
    ]
