# Generated by Django 4.2.23 on 2025-07-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0022_source_evolea"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="nb_t1_available",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="nb_t1_bis_available",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="nb_t2_available",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="nb_t3_available",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="nb_t4_more_available",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
