# Generated by Django 4.2.23 on 2025-07-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0024_tarn_habitat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalsource",
            name="source",
            field=models.CharField(
                choices=[
                    ("acceslibre", "Accèslibre"),
                    ("clef", "CLEF"),
                    ("agefo", "Agefo"),
                    ("espacil", "Espacil"),
                    ("arpej", "Arpej"),
                    ("studefi", "Studefi"),
                    ("sogima", "Sogima"),
                    ("orne-habitat", "Orne Habitat"),
                    ("tarn-habitat", "Tarn Habitat"),
                    ("oh-mon-appart", "Oh Mon Appart"),
                    ("evolea", "Evolea"),
                    ("partelios", "Partelios"),
                    ("seqens", "Seqens/Adlis"),
                    ("parme", "Parme"),
                ],
                default="clef",
                max_length=100,
                verbose_name="Source",
            ),
        ),
    ]
