# Generated by Django 4.2.23 on 2025-08-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0030_source_podeliha"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
