# Generated by Django 4.2.23 on 2025-09-16 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0031_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="accommodation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="externalsource",
            name="source",
            field=models.CharField(
                choices=[
                    ("acceslibre", "Accèslibre"),
                    ("clef", "CLEF"),
                    ("agefo", "Agefo"),
                    ("espacil", "Espacil"),
                    ("arpej", "Arpej"),
                    ("studefi", "Studefi"),
                    ("sogima", "Sogima"),
                    ("orne-habitat", "Orne Habitat"),
                    ("tarn-habitat", "Tarn Habitat"),
                    ("oh-mon-appart", "Oh Mon Appart"),
                    ("evolea", "Evolea"),
                    ("partelios", "Partelios"),
                    ("seqens", "Seqens/Adlis"),
                    ("parme", "Parme"),
                    ("bmh", "Brest Métropole Habitat"),
                    ("nantaise", "Nantaise d'habitation"),
                    ("vendee", "Vendée logement"),
                    ("france-loire", "France Loire"),
                    ("habellis", "Habellis"),
                    ("crous", "Crous"),
                    ("escale-ouest", "Escale Ouest"),
                    ("apheen", "Apheen"),
                    ("podeliha", "Podeliha"),
                    ("mgel", "MGEL"),
                ],
                default="clef",
                max_length=100,
                verbose_name="Source",
            ),
        ),
    ]
