# Generated by Django 4.2.24 on 2025-09-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0032_created_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accommodation",
            name="images_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_accessible_apartments",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_coliving_apartments",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t1",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t1_available",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t1_bis",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t1_bis_available",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t2",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t2_available",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t3",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t3_available",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t4_more",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t4_more_available",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_total_apartments",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="price_max_t1",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="price_max_t1_bis",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="price_max_t2",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="price_max_t3",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="price_max_t4_more",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="price_min",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="price_min_t1",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="price_min_t1_bis",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="price_min_t2",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="price_min_t3",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="price_min_t4_more",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
