# Generated by Django 4.2.24 on 2025-09-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0033_positive_integer_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="accept_waiting_list",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
