# Generated by Django 4.2.24 on 2025-10-13 09:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0034_waiting_list"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accommodation",
            options={"verbose_name": "Accommodation", "verbose_name_plural": "Accommodations"},
        ),
        migrations.AlterModelOptions(
            name="externalsource",
            options={"verbose_name": "External source", "verbose_name_plural": "External sources"},
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="accept_waiting_list",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="Accept waiting list"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="available",
            field=models.BooleanField(default=True, verbose_name="Available"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="bathroom",
            field=models.CharField(
                blank=True,
                choices=[("shared", "Shared"), ("private", "Private")],
                max_length=50,
                null=True,
                verbose_name="Bathroom",
            ),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="bike_storage",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="Bike storage"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="city",
            field=models.CharField(max_length=150, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="common_areas",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="Common areas"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="cooking_plates",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="Cooking plates"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="desk",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="Desk"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="kitchen_type",
            field=models.CharField(
                blank=True,
                choices=[("shared", "Shared"), ("private", "Private")],
                max_length=50,
                null=True,
                verbose_name="Kitchen type",
            ),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="laundry_room",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="Laundry room"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="microwave",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="Microwave"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_accessible_apartments",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="Number of accessible apartments"
            ),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_coliving_apartments",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="Number of coliving apartments"
            ),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t1",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Number of T1"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t1_available",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Number of available T1"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t1_bis",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Number of T1 bis"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t1_bis_available",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Number of available T1 bis"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t2",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Number of T2"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t2_available",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Number of available T2"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t3",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Number of T3"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t3_available",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Number of available T3"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t4_more",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Number of T4"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_t4_more_available",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Number of available T4"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="nb_total_apartments",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Total number of apartments"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="parking",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="Parking"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="postal_code",
            field=models.CharField(max_length=5, verbose_name="Postal code"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="price_max_t1",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Maximum price for T1"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="price_max_t1_bis",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Maximum price for T1 bis"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="price_max_t2",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Maximum price for T2"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="price_max_t3",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Maximum price for T3"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="price_max_t4_more",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Maximum price for T4"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="price_min",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name="Minimum price"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="price_min_t1",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Minimum price for T1"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="price_min_t1_bis",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Minimum price for T1 bis"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="price_min_t2",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Minimum price for T2"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="price_min_t3",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Minimum price for T3"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="price_min_t4_more",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Minimum price for T4"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="published",
            field=models.BooleanField(default=True, verbose_name="Published"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="refrigerator",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="Refrigerator"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="residence_manager",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="Residence manager"),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="residence_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("universitaire-conventionnee", "Résidence Universitaire conventionnée"),
                    ("sociale-jeunes-actifs", "Résidence sociale Jeunes Actifs"),
                    ("intergenerationnelle", "Résidence intergénérationnelle"),
                    ("autre", "Autre"),
                    ("jeunes-travailleurs", "Foyer Jeunes Travailleurs"),
                    ("service-universitaire-privee", "Résidence service / Résidence universitaire privée"),
                    ("mixte-actifs-etudiants", "Résidence mixte jeunes actifs/étudiants"),
                    ("u-crous", "Cité U / résidence traditionnelle CROUS"),
                    ("hoteliere-sociale", "Résidence Hôtelière à vocation sociale"),
                    ("ecole", "Résidence d'école"),
                    ("service-logement", "Service Logement"),
                    ("internat", "Internat"),
                    ("foyer-soleil", "Foyer soleil"),
                ],
                max_length=100,
                null=True,
                verbose_name="Residence type",
            ),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="secure_access",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="Secure access"),
        ),
        migrations.AlterField(
            model_name="externalsource",
            name="source",
            field=models.CharField(
                choices=[
                    ("acceslibre", "Accèslibre"),
                    ("clef", "CLEF"),
                    ("agefo", "Agefo"),
                    ("espacil", "Espacil"),
                    ("arpej", "Arpej"),
                    ("studefi", "Studefi"),
                    ("sogima", "Sogima"),
                    ("orne-habitat", "Orne Habitat"),
                    ("tarn-habitat", "Tarn Habitat"),
                    ("oh-mon-appart", "Oh Mon Appart"),
                    ("evolea", "Evolea"),
                    ("partelios", "Partelios"),
                    ("seqens", "Seqens/Adlis"),
                    ("parme", "Parme"),
                    ("bmh", "Brest Métropole Habitat"),
                    ("nantaise", "Nantaise d'habitation"),
                    ("vendee", "Vendée logement"),
                    ("france-loire", "France Loire"),
                    ("habellis", "Habellis"),
                    ("crous", "Crous"),
                    ("escale-ouest", "Escale Ouest"),
                    ("apheen", "Apheen"),
                    ("podeliha", "Podeliha"),
                    ("mgel", "MGEL"),
                    ("est-habitat", "Est Habitat"),
                ],
                default="clef",
                max_length=100,
                verbose_name="Source",
            ),
        ),
    ]
