# Generated by Django 4.2.25 on 2025-11-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0036_promologis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalsource",
            name="source",
            field=models.CharField(
                choices=[
                    ("acceslibre", "Accèslibre"),
                    ("clef", "CLEF"),
                    ("agefo", "Agefo"),
                    ("espacil", "Espacil"),
                    ("arpej", "Arpej"),
                    ("studefi", "Studefi"),
                    ("sogima", "Sogima"),
                    ("orne-habitat", "Orne Habitat"),
                    ("tarn-habitat", "Tarn Habitat"),
                    ("oh-mon-appart", "Oh Mon Appart"),
                    ("evolea", "Evolea"),
                    ("partelios", "Partelios"),
                    ("seqens", "Seqens/Adlis"),
                    ("parme", "Parme"),
                    ("bmh", "Brest Métropole Habitat"),
                    ("nantaise", "Nantaise d'habitation"),
                    ("vendee", "Vendée logement"),
                    ("france-loire", "France Loire"),
                    ("habellis", "Habellis"),
                    ("crous", "Crous"),
                    ("escale-ouest", "Escale Ouest"),
                    ("apheen", "Apheen"),
                    ("podeliha", "Podeliha"),
                    ("mgel", "MGEL"),
                    ("est-habitat", "Est Habitat"),
                    ("promologis", "Promologis"),
                    ("sacogiva", "Sacogiva"),
                ],
                default="clef",
                max_length=100,
                verbose_name="Source",
            ),
        ),
    ]
