# Generated by Django 4.2.25 on 2025-12-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0039_favorites"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="scholarship_holders_priority",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Priority for scholarship holders"
            ),
        ),
    ]
