# Generated by Django 4.2.26 on 2025-12-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0041_owner_sources"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accommodation",
            old_name="nb_t4_more",
            new_name="nb_t4",
        ),
        migrations.RenameField(
            model_name="accommodation",
            old_name="nb_t4_more_available",
            new_name="nb_t4_available",
        ),
        migrations.RenameField(
            model_name="accommodation",
            old_name="price_max_t4_more",
            new_name="price_max_t4",
        ),
        migrations.RenameField(
            model_name="accommodation",
            old_name="price_min_t4_more",
            new_name="price_min_t4",
        ),
        migrations.AddField(
            model_name="accommodation",
            name="nb_t5",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Number of T5"),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="nb_t5_available",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Number of available T5"),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="nb_t6",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Number of T6"),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="nb_t6_available",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Number of available T6"),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="nb_t7",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Number of T7"),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="nb_t7_available",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Number of available T7"),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="nb_t7_more",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Number of T7 more"),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="nb_t7_more_available",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Number of available T7 more"),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_max_t5",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Maximum price for T5"),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_max_t6",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Maximum price for T6"),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_max_t7",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Maximum price for T7"),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_max_t7_more",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Maximum price for T7 more"),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_min_t5",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Minimum price for T5"),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_min_t6",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Minimum price for T6"),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_min_t7",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Minimum price for T7"),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="price_min_t7_more",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Minimum price for T7 more"),
        ),
    ]
