# Generated by Django 4.2.27 on 2026-01-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0044_alter_externalsource_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="wifi",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="Wifi"),
        ),
    ]
