# Generated by Django 4.2.27 on 2026-02-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0047_alter_externalsource_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalsource",
            name="source",
            field=models.CharField(
                choices=[
                    ("acceslibre", "Accèslibre"),
                    ("clef", "CLEF"),
                    ("agefo", "Agefo"),
                    ("espacil", "Espacil"),
                    ("arpej", "Arpej"),
                    ("studefi", "Studefi"),
                    ("sogima", "Sogima"),
                    ("orne-habitat", "Orne Habitat"),
                    ("tarn-habitat", "Tarn Habitat"),
                    ("oh-mon-appart", "Oh Mon Appart"),
                    ("evolea", "Evolea"),
                    ("partelios", "Partelios"),
                    ("seqens", "Seqens/Adlis"),
                    ("parme", "Parme"),
                    ("bmh", "Brest Métropole Habitat"),
                    ("nantaise", "Nantaise d'habitation"),
                    ("vendee", "Vendée logement"),
                    ("france-loire", "France Loire"),
                    ("habellis", "Habellis"),
                    ("crous", "Crous"),
                    ("escale-ouest", "Escale Ouest"),
                    ("apheen", "Apheen"),
                    ("podeliha", "Podeliha"),
                    ("mgel", "MGEL"),
                    ("est-habitat", "Est Habitat"),
                    ("promologis", "Promologis"),
                    ("sacogiva", "Sacogiva"),
                    ("opal", "Opal"),
                    ("afev", "AFEV"),
                    ("foyer-remois", "Foyer Remois"),
                    ("vichy-habitat", "Vichy Habitat"),
                    ("appartstudy", "Appartstudy"),
                    ("residup", "Résid'Up"),
                    ("alteal", "Alteal"),
                    ("sevre-loire-habitat", "Sevre Loire Habitat"),
                    ("acm-habitat", "ACM Habitat"),
                    ("groupe-3f-cvl", "Groupe 3F CVL"),
                    ("logis-metropole", "Logis Métropole"),
                    ("cardinal-campus", "Cardinal Campus"),
                ],
                default="clef",
                max_length=100,
                verbose_name="Source",
            ),
        ),
    ]
