# Generated by Django 4.2.27 on 2026-02-23 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_student_dossierfacile_metadata"),
        ("accommodation", "0049_alter_externalsource_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccommodationApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("reviewed", "Reviewed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=32,
                    ),
                ),
                ("dossierfacile_status", models.CharField(max_length=64)),
                ("dossierfacile_url", models.URLField(max_length=500)),
                ("dossierfacile_pdf_url", models.URLField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accommodation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="accommodation.accommodation",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accommodation_applications",
                        to="account.student",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "unique_together": {("student", "accommodation")},
            },
        ),
    ]
