# Generated by Django 4.2.27 on 2026-02-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0049_alter_externalsource_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="external_reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="accommodation",
            constraint=models.UniqueConstraint(
                fields=("owner", "external_reference"), name="unique_owner_external_reference"
            ),
        ),
    ]
