# Generated by Django 4.2.27 on 2026-03-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0052_alter_externalsource_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="target_audience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("etudiants", "Etudiants"),
                    ("mixte-etudiants-jeunes-actifs", "Mixte étudiants/jeunes actifs"),
                ],
                max_length=100,
                null=True,
                verbose_name="Target audience",
            ),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="residence_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("universitaire-conventionnee", "Résidence Universitaire conventionnée"),
                    ("sociale-jeunes-actifs", "Résidence sociale Jeunes Actifs (RSJA, Habitat Jeunes)"),
                    ("intergenerationnelle", "Cohabitation intergénérationnelle"),
                    ("jeunes-travailleurs", "Foyer Jeunes Travailleurs (FJT)"),
                    ("social-fleche-jeune", "Logement social fléché vers les jeunes (loi ELAN – article 109)"),
                    ("social-classique", "Logement social classique commercialisé en partie aux étudiants"),
                    ("ecole", "Résidence d’école ou d’établissement d’enseignement"),
                    ("residence-etudiante", "Résidence étudiante"),
                    (
                        "sous-location",
                        "Logements sociaux sous-loués aux étudiants par une association via une convention ou un contrat spécifique",
                    ),
                ],
                max_length=100,
                null=True,
                verbose_name="Residence type",
            ),
        ),
    ]
