# Generated by Django 4.2.27 on 2026-03-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0053_accommodation_target_audience_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accommodation",
            name="residence_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("universitaire-conventionnee", "Résidence Universitaire conventionnée"),
                    ("residence-sociale-jeunes-actifs", "Résidence sociale Jeunes Actifs (RSJA, Habitat Jeunes)"),
                    ("intergenerationnelle", "Cohabitation intergénérationnelle"),
                    ("foyer-jeunes-travailleurs", "Foyer Jeunes Travailleurs (FJT)"),
                    ("loi-elan-article-109", "Logement social fléché vers les jeunes (loi ELAN – article 109)"),
                    ("logement-social-classique", "Logement social classique commercialisé en partie aux étudiants"),
                    ("ecole", "Résidence d’école ou d’établissement d’enseignement"),
                    ("residence-etudiante", "Résidence étudiante"),
                    (
                        "sous-location",
                        "Logements sociaux sous-loués aux étudiants par une association via une convention ou un contrat spécifique",
                    ),
                ],
                max_length=100,
                null=True,
                verbose_name="Residence type",
            ),
        ),
    ]
