# Generated by Django 4.2.17 on 2025-01-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionAnswerGlobal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_fr", models.CharField(max_length=200)),
                ("title_en", models.CharField(blank=True, max_length=200, null=True)),
                ("content_fr", models.TextField()),
                ("content_en", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
