# Generated by Django 4.2.26 on 2026-01-05 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("territories", "0012_est_habitat"),
        ("account", "0004_student_studentregistrationtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccommodationAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "has_coliving",
                    models.BooleanField(blank=True, db_index=True, null=True, verbose_name="Has coliving"),
                ),
                (
                    "is_accessible",
                    models.BooleanField(
                        blank=True, db_index=True, null=True, verbose_name="Accessible for disabled people"
                    ),
                ),
                (
                    "max_price",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name="Maximum price"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("receive_notifications", models.BooleanField(default=True, verbose_name="Receive notifications")),
                (
                    "academy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accommodation_alerts",
                        to="territories.academy",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accommodation_alerts",
                        to="territories.city",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accommodation_alerts",
                        to="territories.department",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accommodation_alerts",
                        to="account.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accommodation alert",
                "verbose_name_plural": "Accommodation alerts",
            },
        ),
    ]
