# Generated by Django 4.2.17 on 2024-12-10 14:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("territories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="academy",
            name="boundary",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name="city",
            name="boundary",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name="department",
            name="boundary",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
