# Generated by Django 4.2.17 on 2024-12-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("territories", "0002_territories_boundary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
