# Generated by Django 4.2.17 on 2025-01-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("territories", "0003_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="average_income",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="insee_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="population",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
