# Generated by Django 4.2.17 on 2025-01-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("territories", "0004_city_insee_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="epci_code",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
