# Generated by Django 4.2.17 on 2025-01-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("territories", "0005_epci_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="popular",
            field=models.BooleanField(default=False),
        ),
    ]
