# Generated by Django 4.2.17 on 2025-01-21 13:46

import autoslug.fields
from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    City = apps.get_model("territories", "City")
    for city in City.objects.all():
        base_slug = slugify(city.name)
        slug = base_slug
        counter = 1

        while City.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        city.slug = slug
        city.save()


class Migration(migrations.Migration):
    dependencies = [
        ("territories", "0006_popular_cities"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="",
                editable=False,
                max_length=255,
                populate_from="name",
                unique=False,
            ),
        ),
        migrations.RunPython(populate_slugs),
    ]
