# Generated by Django 4.2.17 on 2025-01-21 14:04

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("territories", "0007_city_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="",
                editable=False,
                max_length=255,
                populate_from="name",
                unique=True,
            ),
        ),
    ]
