# Generated by Django 4.2.18 on 2025-02-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("territories", "0010_insee_codes_array"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="average_rent",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
