# Generated by Django 4.2.24 on 2025-10-13 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("territories", "0011_average_rent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academy",
            options={"verbose_name": "Academy", "verbose_name_plural": "Academies"},
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "City", "verbose_name_plural": "Cities"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "Country", "verbose_name_plural": "Countries"},
        ),
        migrations.AlterModelOptions(
            name="department",
            options={"verbose_name": "Department", "verbose_name_plural": "Departments"},
        ),
    ]
