# Generated by Django 4.2.27 on 2026-01-26 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("territories", "0012_est_habitat"),
    ]
    operations = [
        migrations.RunSQL(
            sql="""
                CREATE INDEX city_name_fts_idx
                ON territories_city
                USING gin (
                    to_tsvector('simple', name)
                );
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS city_name_fts_idx;
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE INDEX academy_name_fts_idx
                ON territories_academy
                USING gin (
                    to_tsvector('simple', name)
                );
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS academy_name_fts_idx;
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE INDEX department_name_fts_idx
                ON territories_department
                USING gin (
                    to_tsvector('simple', name)
                );
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS department_name_fts_idx;
            """,
        ),
    ]
