# Generated by Django 4.2.27 on 2026-02-09 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("territories", "0013_auto_20260126_1019"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION immutable_unaccent(text)
                RETURNS text
                LANGUAGE sql
                IMMUTABLE
                AS $$
                    SELECT unaccent($1);
                $$;
            """,
            reverse_sql="""
                DROP FUNCTION IF EXISTS immutable_unaccent(text);
            """,
        ),
        # --- FTS indexes with unaccent ---
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS city_name_fts_unaccent_idx
                ON territories_city
                USING gin (
                    to_tsvector('simple', immutable_unaccent(name))
                );
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS city_name_fts_unaccent_idx;
            """,
        ),
        # --- Trigram indexes for icontains ---
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS city_name_trgm_idx
                ON territories_city
                USING gin (immutable_unaccent(name) gin_trgm_ops);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS city_name_trgm_idx;
            """,
        ),
    ]
