# Generated by Django 4.2.23 on 2025-08-05 08:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("territories", "0011_average_rent"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationalInstitution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="Localisation"
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=5)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institutions",
                        to="territories.academy",
                    ),
                ),
            ],
        ),
    ]
